# versioning set this way to be consistent with other intel packages (including their tbb)
{% set version = "2018.0.2" %}

package:
  name: tbb
  version: {{ version }}

source:
  fn: tbb{{ version }}oss_src.tgz
  url: https://github.com/01org/tbb/archive/2018_U2.tar.gz
  sha256: 78bb9bae474736d213342f01fe1a6d00c6939d5c75b367e2e43e7bf29a6d8eca
  patches:
    - 0001-respect-gcc-env-vars.patch
    - 0002-release-build-only.patch

build:
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake  # [win]

test:
  requires:
    - python
  commands:
    - test -f ${PREFIX}/include/tbb/tbb.h  # [unix]
    - python -c "import ctypes; ctypes.cdll[r'${PREFIX}/lib/libtbb${SHLIB_EXT}']"  # [unix]
    - python -c "import ctypes; ctypes.cdll[r'%PREFIX%\Library\bin\tbb.dll']"  # [win]
    - if not exist %PREFIX%\\Library\\include\\tbb\\tbb.h exit 1  # [win]
    - if not exist %PREFIX%\\Library\\lib\\tbb.lib exit 1  # [win]

about:
  home: http://www.threadingbuildingblocks.org
  license: Apache 2.0
  license_file: LICENSE
  summary: High level abstract threading library

extra:
  recipe-maintainers:
    - jschueller
    - msarahan
