{% set name = "tbb" %}
{% set version = "2022.3.0" %}

# https://github.com/uxlfoundation/oneTBB/blob/f1862f38f83568d96e814e469ab61f88336cc595/include/oneapi/tbb/version.h#L48
{% set vinterface = "12170" %}
{% set vbinary = vinterface|int // 1000 %}
{% set vminor = (vinterface|int % 1000 / 10)|int %}
{% set vtag = "v" ~ version.replace(".rc", "-rc") %}

# tbb4py files should be installed into PREFIX.
# See https://docs.conda.io/projects/conda-build/en/latest/user-guide/environment-variables.html.
# On non-Windows CMAKE_ARGS already contains CMAKE_INSTALL_PREFIX.
{% if win %}
    {% set cmake_args = "%CMAKE_ARGS% -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=%LIBRARY_PREFIX%" %}
    {% set cmake_tbb4py_args = "%CMAKE_ARGS% -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=%PREFIX%" %}
{% else %}
    {% set cmake_args = "$CMAKE_ARGS -DCMAKE_BUILD_TYPE=Release" %}
    {% set cmake_tbb4py_args = "$CMAKE_ARGS -DCMAKE_BUILD_TYPE=Release" %}
{% endif %}

# Use specific test list agreed with TBB team to cover core functionality on high level.
# Execution of all tests is too heavy task for packaging CI.
# test_malloc_compliance is temporary excluded from the list since it causes failures that likely appear due to test implementation or env misconfiguration.
# oneTBB issue: https://github.com/oneapi-src/oneTBB/issues/700
# Agreed with oneTBB developers that it is suitable approach since the product is fully tested on oneTBB side.
{% set tests = "test_parallel_for test_tbb_header conformance_version test_flow_graph test_arena_constraints" %}
{% set ctest_regex = "^(%s)$" % (tests.replace(' ', '|')) %}

package:
  name: {{ name }}-split
  version: {{ version }}

source:
  url: https://github.com/oneapi-src/oneTBB/archive/refs/tags/{{ vtag }}.tar.gz
  sha256: 01598a46c1162c27253a0de0236f520fd8ee8166e9ebb84a4243574f88e6e50a
  patches:
    - 0001-fix-setup.patch

build:
  number: 0

outputs:
  - name: {{ name }}
    requirements:
      build:
        - {{ stdlib('c') }}
        - {{ compiler('cxx') }}
        - cmake
        - python
        - ninja-base
        - pkg-config
      host:
        - libhwloc {{ libhwloc }}
    build:
      script:
        - cmake {{ cmake_args }} -GNinja -DTBB_TEST=OFF -S . -B build
        - cmake --build build --parallel
        - cmake -DCOMPONENT=runtime -P build/cmake_install.cmake
    test:
      requires:
        - python
      commands:
        {% set libname = "libtbb.so." ~ vbinary ~ "." ~ vminor %}          # [linux]
        {% set libname = "libtbb." ~ vbinary ~ "." ~ vminor ~ ".dylib" %}  # [osx]
        {% set libname = "tbb" ~ vbinary ~ ".dll" %}                       # [win]
        {% set win_extra = "os.add_dll_directory(os.environ['LIBRARY_BIN']); " if win else "" %}
        - python -c "import ctypes, os; {{ win_extra }} assert {{ vinterface }} == ctypes.cdll[r'{{ libname }}']['TBB_runtime_interface_version']()"
  - name: {{ name }}-devel
    requirements:
      build:
        - {{ stdlib('c') }}
        - {{ compiler('cxx') }}
        - cmake
        - python
        - ninja-base
        - pkg-config
      host:
        - libhwloc {{ libhwloc }}
      run:
        - {{ pin_subpackage('tbb', exact=True) }}  # development package is for specific version of tbb
    build:
      script:
        - cmake {{ cmake_args }} -GNinja -DTBB_TEST=OFF -S . -B build
        - cmake --build build --parallel
        - cmake -DCOMPONENT=devel -P build/cmake_install.cmake
      run_exports:
        - tbb >={{ version }}
    test:
      requires:
        - {{ stdlib('c') }}
        - {{ compiler('cxx') }}
        - cmake
        - python
        - ninja-base
        - pkg-config
      source_files:
        - cmake
        - test
        - CMakeLists.txt
        - include  # some tests depend on files from include
        - integration  # same
        - src  # some tests depend on files from src
      commands:
        # Setting TBB_DIR=ON and TBB_FIND_PACKAGE=ON is needed to use libraries from the tested package,
        # but do not build them from sources; real path to TBBConfig files is not required,
        # because CMake will successfully find installed tested package.
        - cmake {{ cmake_args }} -GNinja -DTBB_TEST=ON -DTBB_DIR=ON -DTBB_FIND_PACKAGE=ON -S . -B test_build
        - cmake --build test_build --target {{ tests }} --parallel  # build tests
        - cd test_build
        - ctest -R "{{ ctest_regex }}" --output-on-failure

  - name: {{ name }}4py
    requirements:
      build:
        - {{ stdlib('c') }}
        - {{ compiler('cxx') }}
        - cmake
        - python
        - ninja-base
        - pkg-config
        - swig
        - setuptools
      host:
        - pip
        - python
        - setuptools
        - {{ pin_subpackage('tbb-devel', exact=True) }}
      run:
        - tbb >={{ version }}  # while python module works with any compatible tbb...
        - python
    build:
      script:
        - cmake {{ cmake_tbb4py_args }} -GNinja -DTBB4PY_BUILD=ON -DTBB_TEST=OFF -S . -B build
        - cmake --build build --target python_build --parallel
        - cmake -DCOMPONENT=tbb4py -P build/cmake_install.cmake
    test:
      requires:
        - python
        - {{ pin_subpackage('tbb', exact=True) }}  # we want to test with this specific tbb package
      imports:
        - tbb
        - TBB
      commands:
        - python -m TBB -h
        - python -m tbb -h
        - python -m tbb test

about:
  home: https://github.com/oneapi-src/oneTBB
  license: Apache-2.0
  license_family: Apache
  license_file:
    - LICENSE.txt
    - third-party-programs.txt
  summary: High level abstract threading library
  description: |
    oneTBB is a flexible C++ library that simplifies the work of adding parallelism to complex applications, even if you
    are not a threading expert.
  dev_url: https://github.com/oneapi-src/oneTBB
  doc_url: https://software.intel.com/en-us/oneapi-tbb-documentation

extra:
  skip-lints:
    - wrong_output_script_key
    - outputs_not_unique
    - missing_section
  recipe-maintainers:
    - anton-malakhov
    - jschueller
    - AlexVeprev
    - isaevil
    - ilya-lavrenov
